# Generated by Django 4.0.4 on 2022-06-24 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maceta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_prod', models.CharField(max_length=64, verbose_name='Nombre_prod')),
                ('descripcion_prod', models.CharField(max_length=100, verbose_name='Descripcion_prod')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('material', models.CharField(max_length=30, verbose_name='Material')),
                ('alto', models.FloatField(verbose_name='Alto')),
                ('ancho', models.FloatField(verbose_name='Ancho')),
                ('largo', models.FloatField(verbose_name='Largo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_prod', models.CharField(max_length=64, verbose_name='Nombre_prod')),
                ('descripcion_prod', models.CharField(max_length=100, verbose_name='Descripcion_prod')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('toxicidad', models.CharField(max_length=40, verbose_name='Toxicidad')),
                ('alto', models.FloatField(verbose_name='Alto')),
                ('ancho', models.FloatField(verbose_name='Ancho')),
                ('largo', models.FloatField(verbose_name='Largo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Sugerencia'], [1, 'Problema'], [2, 'Comentario'], [3, 'Otro']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tierra',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_prod', models.CharField(max_length=64, verbose_name='Nombre_prod')),
                ('descripcion_prod', models.CharField(max_length=100, verbose_name='Descripcion_prod')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Id')),
                ('cantidad', models.IntegerField(verbose_name='cantidad_vendida')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('estado', models.IntegerField(choices=[[0, 'En espera'], [1, 'En camino'], [2, 'Entregado']])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planta')),
            ],
        ),
    ]
