# Generated by Django 4.0.5 on 2022-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscripcion',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
