# Generated by Django 4.0.5 on 2022-06-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
