# Generated by Django 4.0.5 on 2022-07-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boleta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='id',
            field=models.CharField(default='', max_length=24, primary_key=True, serialize=False, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='valor_dscto',
            field=models.FloatField(verbose_name='valor_dscto'),
        ),
    ]
