# Generated by Django 4.0.5 on 2022-07-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_descuento_id_alter_descuento_valor_dscto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
