# Generated by Django 4.0.5 on 2022-07-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscripcion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(default=0, verbose_name='total'),
        ),
    ]
