# Generated by Django 4.0.5 on 2022-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subscripcion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
